# Generated by Django 4.0.6 on 2024-02-04 23:57

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('BaronPropiedades', '0002_alter_client_email_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=250, unique=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='CL', unique=True, verbose_name='Teléfono'),
        ),
    ]
