# Generated by Django 4.0.6 on 2024-02-05 00:10

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('BaronPropiedades', '0003_alter_client_email_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='CL', verbose_name='Teléfono'),
        ),
    ]
