# Generated by Django 4.0.6 on 2024-02-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaronPropiedades', '0005_property_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='available',
            field=models.BooleanField(default=True, verbose_name='¿Disponible?'),
        ),
    ]
