# Generated by Django 4.0.6 on 2024-02-08 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaronPropiedades', '0006_property_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='available',
            new_name='is_available',
        ),
    ]
